USE [master]
GO

/****** Object:  Database [NerdWardrobe]    Script Date: 10/17/2016 2:03:10 PM ******/
CREATE DATABASE [NerdWardrobe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NerdWardrobe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NerdWardrobe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NerdWardrobe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\NerdWardrobe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [NerdWardrobe] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NerdWardrobe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NerdWardrobe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NerdWardrobe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NerdWardrobe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NerdWardrobe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NerdWardrobe] SET ARITHABORT OFF 
GO

ALTER DATABASE [NerdWardrobe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NerdWardrobe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NerdWardrobe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NerdWardrobe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NerdWardrobe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NerdWardrobe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NerdWardrobe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NerdWardrobe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NerdWardrobe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NerdWardrobe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NerdWardrobe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NerdWardrobe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NerdWardrobe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NerdWardrobe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NerdWardrobe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NerdWardrobe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NerdWardrobe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NerdWardrobe] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NerdWardrobe] SET  MULTI_USER 
GO

ALTER DATABASE [NerdWardrobe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NerdWardrobe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NerdWardrobe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NerdWardrobe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NerdWardrobe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NerdWardrobe] SET QUERY_STORE = OFF
GO

USE [NerdWardrobe]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [NerdWardrobe] SET  READ_WRITE 
GO

