//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdWardrobeMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NerdWardrobeEntities : DbContext
    {
        public NerdWardrobeEntities()
            : base("name=NerdWardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Occassion> Occassions { get; set; }
        public virtual DbSet<Outfile> Outfiles { get; set; }
        public virtual DbSet<Pant> Pants { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Shirt> Shirts { get; set; }
        public virtual DbSet<Sho> Shoes { get; set; }
    }
}
