//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdWardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfile
    {
        public int OutfitID { get; set; }
        public Nullable<int> ShirtID { get; set; }
        public Nullable<int> PantsId { get; set; }
        public Nullable<int> AccessoriesID { get; set; }
        public Nullable<int> ShoesID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Pant Pant { get; set; }
        public virtual Shirt Shirt { get; set; }
        public virtual Sho Sho { get; set; }
    }
}
