//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdWardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shirt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shirt()
        {
            this.Outfiles = new HashSet<Outfile>();
        }
    
        public int ShirtID { get; set; }
        public string ShirtName { get; set; }
        public string ShirtType { get; set; }
        public string ShirtColor { get; set; }
        public string ShirtPhoto { get; set; }
        public Nullable<int> OccassionID { get; set; }
        public Nullable<int> SeasonID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Outfile> Outfiles { get; set; }
        public virtual Occassion Occassion { get; set; }
        public virtual Season Season { get; set; }
    }
}
